### PR TITLE
Live logging

### PR DESCRIPTION
**Pull request by freeman-lab**
### live logging

This PR adds support for live logging to the web app, as part of a new status page associated with each repo. See http://dev.mybinder.org/repo/binder-project/example-requirements/status for a preview. There's also a Domino's style tracker :pizza:

This PR, alongside the related changes in https://github.com/binder-project/binder/pull/19 which provides a WebSocket endpoint, is used to display logs during builds that look like this:
### example for success

logging
### example for failure

logging-failure

Also note a UX change: upon clicking "make my binder", we immediately display the status / logger, so the badge markdown / rst is made available there.

There are a couple minor UI things to fix (mainly involving the badge), but this should be closed.

Addresses https://github.com/binder-project/binder/issues/10, cc @mrocklin

### CODE REVIEW

**Comment by freeman-lab** [comment]
Great suggestion from @ahmadia: add a download button next to the logs. Thanks!

**Comment by rgbkrk** [comment]
I love Domino's :pizza:, this is great.

**Comment by andrewosh** [comment]
:hand: Issue that should be fixed before merging: When you click "Build," go to the status page, and then press the back button, the last checked dependency should be selected. Currently, it will always default to "None"

**Comment by freeman-lab** [comment]
Fixed remaining problems, merging in, will deploy to production soon!

**Pull request merged**
